server:
  port: ${AUTHORIZATION_SERVER_SERVER_PORT:9000}

token:
  settings:
    issuer: ${AUTHORIZATION_SERVER_TOKEN_SETTINGS_ISSUER:http://localhost:9000}

logging:
  level:
    org.springframework.web: DEBUG
